In [ ]:
from typing import List

class Solution:
    def rotate(self, matrix: List[List[int]]) -> None:
        """
        Do a vertical flip followed by a transpose
        (sequential Householder transforms for the win)
        """
        n = len(matrix)
        # vertical mirror/flip
        for i in range(n//2):
            for j in range(n):
                matrix[i][j], matrix[n-1-i][j] = matrix[n-1-i][j], matrix[i][j]

        # transpose (diagonal mirror/flip)
        for i in range(n):
            for j in range(i+1, n):
                matrix[i][j], matrix[j][i] = matrix[j][i], matrix[i][j]
    
        return matrix
            

In [ ]:
sol = Solution()

matrix = [[1,2,3],[4,5,6],[7,8,9]]
sol.rotate(matrix)
print(matrix)  # [[7,4,1],[8,5,2],[9,6,3]]

matrix = [[5,1,9,11],[2,4,8,10],[13,3,6,7],[15,14,12,16]]
sol.rotate(matrix)
print(matrix)  # [[15,13,2,5],[14,3,4,1],[12,6,8,9],[16,7,10,11]]

In [1]:
# using just-in-time compiler, need to use numpy because numba doesn't like List[List[int]]

import numpy as np
from numba import njit
from typing import List

@njit
def rotate_matrix_numpy(matrix: np.ndarray) -> None:
    """
    Rotate matrix 90 degrees clockwise using NumPy array
    Do a vertical flip followed by a transpose
    """
    n = matrix.shape[0]
    # vertical mirror/flip
    for i in range(n//2):
        for j in range(n):
            matrix[i][j], matrix[n-1-i][j] = matrix[n-1-i][j], matrix[i][j]

    # transpose (diagonal mirror/flip)
    for i in range(n):
        for j in range(i+1, n):
            matrix[i][j], matrix[j][i] = matrix[j][i], matrix[i][j]

class Solution:
    def rotate(self, matrix: np.ndarray) -> None:
        rotate_matrix_numpy(matrix)
        return matrix

In [2]:
sol = Solution()

matrix = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype=np.int64)
sol.rotate(matrix)
print(matrix)  # [[7,4,1],[8,5,2],[9,6,3]]

matrix = np.array([[5,1,9,11],[2,4,8,10],[13,3,6,7],[15,14,12,16]], dtype=np.int64)
sol.rotate(matrix)
print(matrix)  # [[15,13,2,5],[14,3,4,1],[12,6,8,9],[16,7,10,11]]

[[7 4 1]
 [8 5 2]
 [9 6 3]]
[[15 13  2  5]
 [14  3  4  1]
 [12  6  8  9]
 [16  7 10 11]]


In [ ]:
import sys
print(f"Python executable: {sys.executable}")
print(f"Python version: {sys.version}")